server:
  port: 8082

spring:
  application:
    name: transaction_service

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: transaction-events

  data:
    mongodb:
      uri: mongodb+srv://dewanganbackup_db_user:${MONGO_PASSWORD}@transaction.6nlfagz.mongodb.net/safepay_reward_db?appName=transaction
      database: transactionService
