server:
  port: 8080

spring:
  application:
    name: api_gateway_service

  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

          routes:
            # User microservice
            - id: user_service
              uri: http://localhost:8081
              predicates:
                - Path=/auth/**

            # Transaction microservice
            - id: transaction_service
              uri: http://localhost:8082
              predicates:
                - Path=/api/transactions/**

            # Reward microservice
            - id: reward_service
              uri: http://localhost:8089
              predicates:
                - Path=/api/rewards/**

            # Notification microservice
            - id: notification_service
              uri: http://localhost:8084
              predicates:
                - Path=/api/notify/**
